
[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git


[supertux88]
location = /var/db/repos/supertux88
sync-type = git
sync-uri = https://github.com/gentoo-mirror/supertux88.git
