[default]
depends = ["hyprland", "zsh", "git", "nvim", "ags"]

[hyprland]
depends = ["eww", "kitty", "swaylock"]

[hyprland.files]
hyprland = "~/.config/hypr"
"hyprland/toggle_touchpad.sh" = "~/.local/bin/toggle_touchpad"

[zsh.files]
"zsh/zshrc" = "~/.zshrc"
zsh = "~/.config/zsh"

[alacritty.files]
"term-emulators/alacritty.yml" = "~/.config/alacritty/alacritty.yml"

[kitty.files]
"term-emulators/kitty.conf" = { target="~/.config/kitty/kitty.conf", type="symbolic" }

[swaylock.files]
"swaylock/config" = "~/.config/swaylock/config"
"swaylock/lock.sh" = "~/.local/bin/lock"
"swaylock/idle.sh" = "~/.local/bin/swayidle-daemon"

[eww.files]
eww = "~/.config/eww"

[ags.files]
ags = "~/.config/ags"

[nvim.files]
nvim = "~/.config/nvim"

[ssh.files]
ssh = "~/.ssh"
"secrets/ssh" = "~/.ssh"

[git.files]
"other/git.ini" = "~/.gitconfig"

[rclone.files]
"secrets/rclone.conf" = "~/.config/rclone/rclone.conf"
