source /usr/share/zsh/themes/powerlevel10k/powerlevel10k.zsh-theme

autoload -Uz compinit promptinit
compinit -d ~/.cache/zcompdump
promptinit; prompt gentoo

export DOTNET_CLI_TELEMETRY_OPTOUT=1

alias yt-dlp="yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'"
alias yoink="git clone --depth 1 --recurse-submodules"
alias reload="source ~/.zshrc; rehash"
alias vi=nano

alias emerge-sync="sudo emaint sync -a"
alias emerge-update="sudo emerge -NDuq @world"
alias emerge-clean="sudo emerge --depclean; sudo eclean-dist -d"

alias emerge-full="emerge-sync; emerge-update; emerge-clean"
alias update="emerge-full; sudo flatpak update -y; rustup update"

bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word
bindkey "^[[3~" delete-char
bindkey '^H' backward-kill-word
bindkey '5~' kill-word

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.config/zsh/p10k.zsh ]] || source ~/.config/zsh/p10k.zsh
