source /usr/share/zsh/themes/powerlevel10k/powerlevel10k.zsh-theme

autoload -Uz compinit promptinit
compinit -d ~/.cache/zcompdump
promptinit; prompt gentoo

export DOTNET_CLI_TELEMETRY_OPTOUT=1
export PATH="$HOME/.local/bin:$PATH"
export EDITOR="nvim"

alias yt-dlp="yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'"
alias compress="GZIP=-9 tar cvzf compressed.tar.xz"
alias yoink="git clone --depth 1 --recurse-submodules"
alias reload="source ~/.zshrc; rehash"

alias emerge-sync="sudo emaint sync -a"
alias emerge-update="sudo emerge -NDuq @world --keep-going"
alias emerge-clean="sudo emerge --depclean; sudo eclean-dist -d"

alias emerge-full="emerge-sync; emerge-update; emerge-clean"
alias update="emerge-full; sudo flatpak update -y"

HISTFILE=~/.local/state/zsh_history
HISTSIZE=1000
SAVEHIST=1000
setopt INC_APPEND_HISTORY_TIME

bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word
bindkey "^[[3~" delete-char
bindkey '^H' backward-kill-word
bindkey '5~' kill-word

[[ ! -f ~/.config/zsh/p10k.zsh ]] || source ~/.config/zsh/p10k.zsh
